version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
  python:
    build: 
      dockerfile: Dockerfile_python
    command: flask run
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
    ports:
      - "${PYTHON_EXTERNAL_PORT}:5000"
    volumes:
      - python-code:/code
  svelte:
    build:
      dockerfile: Dockerfile_svelte
    command: npm run dev -- --host --port 8080
    ports:
      - "${SVELTE_EXTERNAL_PORT}:8080"
    volumes:
      - svelte-code:/app

volumes:
  db:
    driver: local
  python-code:
    driver: local
    driver_opts:
      type: none
      device: python_app_code
      o: bind
  svelte-code:
    driver: local
    driver_opts:
      type: none
      device: svelte_app_code/vitualization-level-1-prototype-app-svelte
      o: bind
