version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5000:5432"
    volumes:
      - db:/var/lib/postgresql/data
  python:
    build: 
      dockerfile: Dockerfile_python
    command: flask run
    environment:
      - FLASK_DEBUG=true
    ports:
      - "5001:5000"
    volumes:
      - code:/code
#  svelte:
#    build:
#      context: ./svelte-app
#      dockerfile: Dockerfile
#    command: npm run dev
#    ports:
#      - "5002:5000"
#    volumes:
#      - svelte-code:/app

volumes:
  db:
    driver: local
  code:
    driver: local
    driver_opts:
      type: none
      device: python_app_code
      o: bind
#  svelte-code:
#    driver: local
