version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5000:5432"
    volumes:
      - db:/var/lib/postgresql/data
  python:
    build: .
    command: flask run
    environment:
      - FLASK_DEBUG=true
    ports:
      - "5001:5000"
    volumes:
      - code:/code

volumes:
  db:
    driver: local
  code:
    driver: local
    driver_opts:
      type: none
      device: python_app_code
      o: bind