# syntax=docker/dockerfile:1
FROM node:lts-alpine AS build

WORKDIR /app

# The svelte project must be initialized in the working directory otherwise the build will fail
COPY ./svelte_app_code/vitualization-level-1-prototype-app-svelte/package*.json ./
RUN rm -rf node_modules
RUN rm -rf build
COPY ./svelte_app_code/vitualization-level-1-prototype-app-svelte .
RUN npm install
RUN npm run build

# Multistage compose was chosen to reduce the size of the final image
#FROM node:lts-alpine AS run
#
#WORKDIR /app
#COPY --from=build /app/package.json ./package.json
#COPY --from=build /app/build ./build
#RUN npm install --production
#
EXPOSE 8080
#ENTRYPOINT [ "npm", "run", "start" ]