# syntax=docker/dockerfile:1
FROM node:lts-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN rm -rf node_modules
RUN rm -rf build
COPY . .
RUN npm install

# Uncomment the following line to start the app project from scratch
RUN npm create svelte@latest

RUN npm run build

# Multistage compose was chosen to reduce the size of the final image
FROM node:lts-alpine AS run

WORKDIR /app
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/build ./build
RUN npm install --production

EXPOSE 8080
ENTRYPOINT [ "npm", "run", "start" ]